# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Database
version:      1.14
version_from: lib/LEOCHARRE/Database.pm
installdirs:  site
requires:
    Carp:                          0
    DBD::mysql:                    0
    DBD::SQLite:                   0
    DBI:                           0
    LEOCHARRE::DEBUG:              0
    Test::Simple:                  0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
