# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Database
version:      1.13
version_from: lib/LEOCHARRE/Database.pm
installdirs:  site
requires:
    DBD::mysql:                    0
    DBD::SQLite:                   0
    DBI:                           0
    LEOCHARRE::DEBUG:              1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
